[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/auth/signup"
  to = "/.netlify/functions/signup"
  status = 200

[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/api/auth/change-password"
  to = "/.netlify/functions/change-password"
  status = 200
